spring:
  application:
    name: Orders
  datasource:
    url: jdbc:mysql://localhost:3307/orders
    username: root
    password: Unir1234
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: DEBUG

catalogue:
  base-url: http://localhost:8085
